# Generated by Django 3.0.5 on 2020-05-25 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurular',
            name='duyurular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 18, 31, 2, 31118, tzinfo=utc), verbose_name='Yayınlandığı Tarih'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 25, 18, 31, 2, 31445, tzinfo=utc)),
        ),
    ]
