# Generated by Django 3.0.5 on 2020-06-09 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinavlar', '0002_auto_20200609_1044'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deneme_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='duyurular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 10, 44, 54, 545709, tzinfo=utc), verbose_name='Yayınlandığı Tarih'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 9, 10, 44, 54, 546121, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_sayisi', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userr', to=settings.AUTH_USER_MODEL)),
                ('yanlis_sorular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soru', to='sinavlar.Soru')),
                ('yapilan_testler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='sinavlar.Test')),
            ],
        ),
    ]
