# Generated by Django 3.0.5 on 2020-06-02 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersler_title', models.CharField(max_length=200)),
                ('dersler_content', models.TextField()),
                ('dersler_published', models.DateTimeField(verbose_name='Yayınlandığı tarih')),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_title', models.CharField(max_length=200)),
                ('kategori_content', models.TextField()),
                ('kategori_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konular_title', models.CharField(max_length=200)),
                ('konular_content', models.TextField()),
                ('konular_published', models.DateTimeField(default=datetime.datetime(2020, 6, 2, 18, 49, 53, 825272, tzinfo=utc), verbose_name='Yayınlandığı tarih')),
                ('konular_slug', models.CharField(default=1, max_length=200)),
                ('konular_ders', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sinavlar.Ders', verbose_name='Ders')),
            ],
            options={
                'verbose_name_plural': 'Konular',
            },
        ),
        migrations.CreateModel(
            name='Yayın',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayin_title', models.CharField(max_length=200)),
                ('yayin_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Yayın',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_buyuk_title', models.CharField(max_length=200, verbose_name='Genel Başlık')),
                ('test_alt_title', models.CharField(max_length=200, verbose_name='Alt Başlık')),
                ('test_slug', models.CharField(max_length=200)),
                ('test_fiyat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_published', models.DateTimeField(default=datetime.datetime(2020, 6, 2, 18, 49, 53, 825994, tzinfo=utc), verbose_name='Yayınlandığı tarih')),
                ('test_sayi', models.PositiveSmallIntegerField()),
                ('test_konu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Konu', verbose_name='Ders')),
                ('test_yayin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='yayin', to='sinavlar.Yayın', verbose_name='Yayın')),
            ],
            options={
                'verbose_name_plural': 'Testler',
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_soru', models.TextField()),
                ('soru_sirasi', models.CharField(default='Soru ', max_length=100)),
                ('soru_test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Test', verbose_name='Test')),
            ],
            options={
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.AddField(
            model_name='ders',
            name='dersler_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sinavlar.Kategori', verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap_content', models.TextField()),
                ('cevap_position', models.PositiveSmallIntegerField(default=0)),
                ('cevap_correct_anwser', models.BooleanField(default=False)),
                ('cevap_soru', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Soru', verbose_name='Soru')),
            ],
            options={
                'verbose_name_plural': 'Cevaplar',
                'ordering': ('cevap_position',),
                'unique_together': {('cevap_soru', 'cevap_content'), ('cevap_soru', 'cevap_position')},
            },
        ),
    ]
