# Generated by Django 3.0.5 on 2020-05-25 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersler_title', models.CharField(max_length=200)),
                ('dersler_content', models.TextField()),
                ('dersler_published', models.DateTimeField(verbose_name='Yayınlandığı tarih')),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_title', models.CharField(max_length=200)),
                ('kategori_content', models.TextField()),
                ('kategori_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Konular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konular_title', models.CharField(max_length=200)),
                ('konular_content', models.TextField()),
                ('konular_published', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 18, 26, 33, 911316, tzinfo=utc), verbose_name='Yayınlandığı tarih')),
                ('konular_slug', models.CharField(default=1, max_length=200)),
                ('konular_ders', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sinavlar.Dersler', verbose_name='Ders')),
            ],
            options={
                'verbose_name_plural': 'Konular',
            },
        ),
        migrations.AddField(
            model_name='dersler',
            name='dersler_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sinavlar.Kategori', verbose_name='Kategori'),
        ),
    ]
