# Generated by Django 3.0.5 on 2020-06-09 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konu',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 10, 44, 54, 543001, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 10, 44, 54, 544149, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
