# Generated by Django 3.0.5 on 2020-05-25 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0002_auto_20200525_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 18, 31, 2, 33215, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
