# Generated by Django 3.0.5 on 2020-05-26 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0003_auto_20200525_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yayın',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayin_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 10, 45, 9, 961695, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.CreateModel(
            name='Testler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_publisher', models.CharField(max_length=200)),
                ('test_slug', models.CharField(max_length=200)),
                ('test_published', models.DateTimeField(default=datetime.datetime(2020, 5, 26, 10, 45, 9, 962352, tzinfo=utc), verbose_name='Yayınlandığı tarih')),
                ('test_ders', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Konular', verbose_name='Ders')),
                ('test_yayin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Yayın', verbose_name='Yayın')),
            ],
            options={
                'verbose_name_plural': 'Testler',
            },
        ),
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_soru', models.TextField()),
                ('soru_sirasi', models.CharField(default='Soru ', max_length=100)),
                ('soru_test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Testler', verbose_name='Test')),
            ],
            options={
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap_content', models.CharField(max_length=100)),
                ('cevap_position', models.PositiveSmallIntegerField(default=0)),
                ('cevap_correct_anwser', models.BooleanField(default=False)),
                ('cevap_soru', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sinavlar.Sorular', verbose_name='Soru')),
            ],
            options={
                'verbose_name_plural': 'Cevaplar',
                'ordering': ('cevap_position',),
                'unique_together': {('cevap_soru', 'cevap_position'), ('cevap_soru', 'cevap_content')},
            },
        ),
    ]
