# Generated by Django 3.0.5 on 2020-05-26 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0004_auto_20200526_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yayın',
            options={'verbose_name_plural': 'Yayın'},
        ),
        migrations.AddField(
            model_name='yayın',
            name='yayin_slug',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 11, 31, 48, 842170, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 11, 31, 48, 842886, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
