# Generated by Django 3.0.5 on 2020-05-26 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0005_auto_20200526_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='yayın',
            name='yayin_konu',
            field=models.ManyToManyField(to='sinavlar.Konular'),
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 41, 37, 524544, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 41, 37, 525720, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
