# Generated by Django 3.0.5 on 2020-05-26 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0006_auto_20200526_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yayın',
            name='yayin_konu',
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 19, 59, 1, 955605, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 19, 59, 1, 956329, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
