# Generated by Django 3.0.5 on 2020-05-27 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0007_auto_20200526_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testler',
            name='test_publisher',
        ),
        migrations.AddField(
            model_name='testler',
            name='test_fiyat',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 13, 48, 58, 375736, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 13, 48, 58, 376514, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
