# Generated by Django 3.0.5 on 2020-05-27 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0009_auto_20200527_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testler',
            old_name='test_ders',
            new_name='test_konu',
        ),
        migrations.RemoveField(
            model_name='testler',
            name='test_title',
        ),
        migrations.AddField(
            model_name='testler',
            name='test_alt_title',
            field=models.CharField(default='0', max_length=200, verbose_name='Alt Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testler',
            name='test_buyuk_title',
            field=models.CharField(default='0', max_length=200, verbose_name='Genel Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 15, 52, 48, 568394, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 15, 52, 48, 569155, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
