# Generated by Django 3.0.5 on 2020-05-28 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sinavlar', '0010_auto_20200527_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='cevap_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='konular',
            name='konular_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 12, 46, 34, 102411, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 12, 46, 34, 103131, tzinfo=utc), verbose_name='Yayınlandığı tarih'),
        ),
    ]
